# Generated by Django 4.0.3 on 2024-02-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
