# Generated by Django 4.0.3 on 2024-02-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], max_length=25),
        ),
    ]
