# Generated by Django 4.0.3 on 2024-02-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_VIP',
            field=models.BooleanField(default=False),
        ),
    ]
